@conversationId = "476310a0-a839-42e3-b63c-b4353f56e81e"

POST http://localhost:7242/api/chuckchat
Content-Type: application/json

{
    "Content" : "Quando è nato Chuck?",
    "ConversationId" : {{conversationId}}
}
###

POST http://localhost:7242/api/chuckchat
Content-Type: application/json

{
    "Content" : "ha vinto qualche premio?",
    "ConversationId" : {{conversationId}}
}
###

POST http://localhost:7242/api/chuckchat
Content-Type: application/json

{
    "Content" : "mi racconti un aneddoto divertente?",
    "ConversationId" : {{conversationId}}
}
###
